dependencies {
    implementation project(':model')
    implementation project(':usecase')

    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb-reactive'
    implementation 'org.reactivecommons.utils:object-mapper-api:0.1.0'

    runtimeOnly 'de.flapdoodle.embed:de.flapdoodle.embed.mongo:4.21.0'
    testImplementation 'org.reactivecommons.utils:object-mapper:0.1.0'

    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
}
